services:
  fe:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8000}
        VITE_WS_URL: ${VITE_WS_URL:-ws://localhost:8000}
    image: monitor-vehicle-ee-fe:latest
    container_name: monitor-vehicle-ee-fe
    ports:
      - "80:80"
    restart: unless-stopped
